### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by lantwi** [lantwi/Game#2]
##### WHAT USER STORY YOU ARE WORKING ON:

I am working on the user story "User wants to alternate turns."
##### WHAT YOU ARE TRYING TO DO:

I am trying to add a click event and assign the colors to the value.
##### DETAILED DESCRIPTION OF THE BUG/ERROR:

I having trouble the function that would link to the click event
## WHAT I'VE TRIED

I have tired using the tic tac toe game as a reference point. Also tried googling click evenys.
[picture of the view]
## QUESTION

What do I need to create the function for the click event, so each individual cell changes value.

@jasonseminara @amcooper

**Comment by jasonseminara** [comment]
Is this still relevant?

**Comment by lantwi** [comment]
No from the first project

On Friday, November 6, 2015, Jason Seminara notifications@github.com
wrote:

> Is this still relevant?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lantwi/Game/issues/2#issuecomment-154437641.

## 

Thank You,
Lesley Antwi
https://www.linkedin.com/in/lesleyantwi
